<?php

/**
 * @file
 * Contains sapi.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sapi_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sapi module.
    case 'help.page.sapi':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Statistics API (v2)') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function sapi_theme() {
  $theme = [];
  $theme['sapi_storage'] = [
    'render element' => 'elements',
    'file' => 'sapi_storage.page.inc',
    'template' => 'sapi_storage',
  ];
  $theme['sapi_storage_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'sapi_storage.page.inc',
  ];
  return $theme;
}
